### ISSUE TITLE
linux debian / styles.css / not working

### ISSUE THREAD

**Issue by deltahoch3** [johannesjo/super-productivity-themes#3]
howdy i would love to use the nordtheme for SP (which is absolutly awesome btw ;) )

i copied it straight into my ~/.config/superProductivity/styles.css

but its not loading, is this only for mac?

i run SP via AppImage or is this maybe the problem?

thanks in advanced and keep it up!
Hardy

**Comment by johannesjo** [comment]
No it should work on any system. Is there some output if you start the app from the commandline?

**Comment by deltahoch3** [comment]
stupid me, I used the wrong files (i picked the css under source, not dist)....
thanks for reaching out

now it works!

**Comment by deltahoch3** [comment]
can be closed ;)
